name: InfrastructureNetwork CI

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
    workflow_dispatch:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Check out
        uses: actions/checkout@v4

      - name: Configure Git to use SSH
        run: git config --add url."git@github.com:".insteadOf "https://github.com/"

      - name: Build and test
        run: |
          swift build
          swift test