name: InfrastructureNetwork CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-15
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Use Xcode 16.2
        run: sudo xcode-select --switch /Applications/Xcode_16.2.app

      - name: Run linter
        run: |
          swift format --recursive --in-place .
          git diff --exit-code
        shell: bash

      - name: Build and test
        run: |
          swift build
          swift test
