name: InfrastructureNetwork CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-13
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Configure Git for HTTPS Authentication
        run: |
          git config --global url."https://x-access-token:${{ secrets.IUNE_CO_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Use Xcode 15.1
        run: sudo xcode-select --switch /Applications/Xcode_15.1.app

      - name: Build and test
        run: |
          swift build
          swift test
